name: tcav_all_datasets
channels:
  - pytorch
  - conda-forge
  - defaults

variables:
  TOKENIZERS_PARALLELISM: "false"       # silence HF tokenizer fork warning
  PYTORCH_ENABLE_MPS_FALLBACK: "1"      # allow MPS→CPU fallback for odd ops

dependencies:
  # --- Core ---
  - python=3.10
  - pip
  - ipykernel
  - jupyterlab

  # --- Numerics / data / viz ---
  - numpy=1.26.*
  - scipy>=1.11
  - pandas>=2.1,<3
  - scikit-learn>=1.4,<2
  - matplotlib>=3.7,<4
  - seaborn>=0.13
  - pyarrow
  - joblib
  - tqdm
  - pyyaml

  # --- Imaging (fixes torchvision libjpeg/libpng warnings) ---
  - pillow>=10
  - jpeg=9*           # provides libjpeg.9.dylib for torchvision
  - libpng

  # --- PyTorch (macOS / MPS) ---
  - pytorch::pytorch=2.6.*
  - pytorch::torchvision=0.21.*
  - pytorch::torchaudio=2.6.*

  # --- NLP / Transformers stack ---
  - conda-forge::transformers>=4.44,<5
  - conda-forge::tokenizers>=0.19
  - conda-forge::safetensors>=0.4
  - conda-forge::accelerate>=0.30
  - conda-forge::huggingface_hub>=0.23

  # --- spaCy (for your text pipeline when not using torchtext) ---
  - spacy>=3.7

  # (Optional) visualization helpers
  # - plotly

  - pip:
      - captum==0.6.0
      - sentencepiece>=0.2.0
      - ucimlrepo
      - openml
      - datasets>=2.19
      # INTENTIONALLY no torchtext here; see optional section below
